brew "atuin"
brew "git-town"
brew "uv"
cask "visual-studio-code"
mas "Telegram", id: 747648890
vscode "charliermarsh.ruff"
vscode "humao.rest-client"
vscode "mhutchie.git-graph"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "redhat.vscode-yaml"
vscode "tamasfe.even-better-toml"
