[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 14

[general]
import = ["~/.config/alacritty/themes/themes/sonokai.toml"]

[keyboard]
bindings = [
    { key = "Left", mods = "Alt", chars = "\u001bB" },       # Skip word left
    { key = "Right", mods = "Alt", chars = "\u001bF" },      # Skip word right
    { key = "Left", mods = "Command", chars = "\u001bOH" },
    { key = "Right", mods = "Command", chars = "\u001bOF" },
]
